config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

	devise_for :users
  devise_for :educs
  devise_for :admins

	namespace :backoffice do
		resources :admin_profiles,
		:educ_profiles,
		:user_profiles,
		:programs,
		:projects,
		:enrollments,
		:classrooms,
		:lessons,
		:attendances
	 get '/analytics', to: 'analytics#index'
	 get '/users_reports', to: 'analytics#users_reports'
	 get '/enrollments_reports', to: 'analytics#enrollments_reports'
	 get '/projects_reports', to: 'analytics#projects_reports'
	 get '/project_report/:id', to: 'analytics#project_report', as: 'project_report'
	end
end

app/models/admin_profile.rb
class AdminProfile < ApplicationRecord
  belongs_to :admin
end

app/controllers/backoffice/admin_profiles_controller.rb
class Backoffice::AdminProfilesController < ApplicationController
  before_action :authenticate_admin!
	before_action :set_admin_profile, only: [:show, :edit]
	layout 'admins'
	def index
		@admin_profiles = AdminProfile.all
  end

	def show
	end

	def new
		@admin_profile = AdminProfile.new
	end

	def create
		@admin_profile = AdminProfile.new(admin_profile_params)
		if @admin_profile.save
			redirect_to backoffice_admin_profile_path(@admin_profile), notice: "#{t('devise.registrations.signed_up', resource_name: @admin_profile.name)}"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @admin_profile.update_with_password(params_admin_profile)
			redirect_to backoffice_admin_profile_path(@admin_profile), notice: "#{t('devise.registrations.updated', resource_name: @admin_profile.name)}"
		else
			render :edit
		end
	end

	def destroy
	end

	private

	def admin_profile_params
		params.require(:admin_profile).permit(:name, :role, :active,
			user_attributes: [:email, :current_password, :password, :password_confirmation]
		)
	end
	
	def set_admin_profile
		@admin_profile = AdminProfile.find(params[:id])
	end
end

app/controllers/backoffice/analytics_controller.rb
class Backoffice::AnalyticsController < ApplicationController
  before_action :authenticate_admin!
	layout 'analytics'
	
	def index
		users_reports
		enrollments_reports
		projects_reports
		total_attended
		total_open_lessons
	end

	def total_attended
		@total_attended = Attendance.where(attended: true).count
	end

	def total_open_lessons
		@total_open_lessons = Lesson.where(status: 'open').count
	end

	def attendances_in_month()
		Attendance.attended_in_month(start_date, end_date, project_ids).count
	end

	def open_lessons_in_month()
		Lesson.open_in_month(start_date, end_date, project_ids).count
	end

	def users_reports
		@user_profiles = UserProfile.all.count
		@active_user_profiles = UserProfile.active.count
		@inactive_user_profiles = UserProfile.inactive.count
	end

	def enrollments_reports
		@enrollments = Enrollment.all.count
		@active_enrollments = Enrollment.active.count
		@canceled_enrollments = Enrollment.canceled.count
	end

	def projects_reports
		@projects = Project.all
		@project_attendance_counts = Attendance.attendance_counts_by_project(@projects)
	end

	def project_report
		@project = Project.find(params[:id])
		@project_attendance_counts = Attendance.attended_by_project(@project).count
		@project_lesson_counts = Lesson.open_by_project(@project.id).count
		@project_active_enrollment_counts = @project.enrollments.active.count
		@project_canceled_enrollment_counts = @project.enrollments.canceled.count
	end
end

app/controllers/backoffice/attendances_controller.rb
class Backoffice::AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update]
	
	def index
		@attendances = Attendance.all
  end

	def show
	end

	def new
		@attendance = Attendance.new
	end

	def create
		@attendance = Attendance.new(attendance_params)
		if @attendance.save!
			flash[:notice] = "Frequência Cadastrada"
		else
			redirect_to backoffice_classrooms_path, status: :unprocessable_entity
		end
	end

	def edit
		@attendance = Attendance.find(params)
	end

	def update
		if @attendance.update(attendance_params)
			flash[:notice] = "Frequência Atualizada"
		end
	end

	private

	def set_attendance
		@attendance = Attendance.find(params[:id])
	end

	def attendance_params
		params.require(:attendance).permit(:attended, :lesson_id, :user_profile_id)
	end
end

app/controllers/backoffice/classrooms_controller.rb
class Backoffice::ClassroomsController < ApplicationController
	layout 'admins'
	before_action :set_classroom, only: [:show, :update]
	before_action :set_projects_and_ceics, only: :index

	def index
		@classrooms = Classroom.page(params[:page]).find_classrooms(params)
  end

	def show
		@classroom_month_lessons = @classroom.month_lessons(classroom_params)
		@attendances = @classroom.lessons_attendances(@classroom_month_lessons)
		@user_profiles = @classroom.user_profile_attendances(@attendances)
	end

	def find_classroom_users
		enroll = Enrollment.where(classroom_id: params[:id])
	end

	private

	def classroom_params
		params.permit(:id, :month, :schedule, :active, :project_id, :ceic_id)
	end
	
	def set_classroom
		@classroom = Classroom.find(params[:id])
	end

	def set_projects_and_ceics
		@projects = Project.all
		@ceics = Ceic.all
	end
end

app/controllers/backoffice/educ_profiles_controller.rb
class Backoffice::EducProfilesController < ApplicationController
	before_action :authenticate_educ!, except: [:index, :new, :create]
	before_action :set_classroom_educ, only: [:show, :update]
	before_action :educ_layout, except: [:index, :new, :create]
	
	def index
		@educ_profiles = EducProfile.all
	end

	def show
		@classroom = Classroom.where(projec_id: @educ_profile.project_id, ceic_id: @educ_profile.ceic_id)
	end

	def new
		@educ_profile = EducProfile.new
	end

	def create
		@educ_profile = EducProfile.new(educ_profile_params)
		if @educ_profile.save
			redirect_to backoffice_educ_profiles_path, notice: "#{t('devise.registrations.signed_up', resource_name: @educ_profile.name)}"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @educ_profile.update_with_password(params_educ)
			redirect_to backoffice_educ_profile_path(@educ_profile), notice: "#{t('devise.registrations.updated', resource_name: @educ_profile.name)}"
		else
			render :edit
		end
	end

	def destroy
	end

	private
	
	def educ_layout
		render :layout => 'educs'
	end

	def set_classroom_educ
		@educ_profile = EducProfile.find(params[:id])
		@classrooms = Classroom.where(project_id: @educ_profile.project_id, ceic_id: @educ_profile.ceic_id)
	end
	
	def educ_profile_params
		params.require(:educ).permit(:name, :email, :current_password, :password, :password_confirmation, :project_id, :ceic_id)
	end
	end

app/controllers/backoffice/enrollments_controller.rb
class Backoffice::EnrollmentsController < ApplicationController
  layout 'admins'

	before_action :set_enrollment, only: [:show, :edit]

	def index
		@enrollments = Enrollment.order(:id).page(params[:page])
	end

	def show
	end

	def new
		@enrollment = Enrollment.new
	end

	def create
		@enroll = Enrollment.new(enrollment_params)
	end

	def edit
	end

	private

	def set_enrollment
		@enrollment = Enrollment.find(params[:id])
	end

		def enrollment_params
		params.require(:enrollment).permit(:canceled, :project_id, :ceic_id, :classroom_id)
	end
end

app/controllers/backoffice/lessons_controller.rb
class Backoffice::LessonsController < ApplicationController
	before_action :authenticate_admin!
	before_action :set_lesson, only: [:show, :edit, :update]
	before_action :set_projects, only: :new
	layout 'admins'

	CURRENT_YEAR = Date.current.year

	def index
		@classrooms = Classroom.all
		@lessons = Lesson.page(params[:page]).search(params)
  end

	def show
	end

	def new
		@lesson = Lesson.new
		@months_available = @lesson.new_lessons_months_allowed
	end

	def create
		year = CURRENT_YEAR
		month = Date::MONTHNAMES.index(params[:month])
		project = Project.find(params[:project_id])
		weekdays = params[:weekdays][:weekdays].reject(&:empty?)
		matching_dates = {}
		weekdays.each do |weekday|
			start_date = Date.new(year, month, 1)
			end_date = Date.new(year, month, -1)

			matching_dates_for_weekdays = []

			current_date = start_date
			while current_date <= end_date
				if weekdays.include?(current_date.wday.to_s)
					matching_dates_for_weekdays << current_date
				end
					current_date += 1
					matching_dates = matching_dates_for_weekdays
			end
		end
		matching_dates.each do |date|
			classroom_ids = project.classrooms.ids
			classrooms = Classroom.find(classroom_ids)
			classrooms.each do |classroom|
				if lesson = Lesson.create!(
					date: date,
					classroom: classroom
					)
					classroom.enrollments.each do |enrollment|
						Attendance.create!(
							lesson: lesson,
							user_profile_id: enrollment.user_profile_id
						)
					end
					flash[:success] = "Aulas adicionadas com sucesso!"
				else
					flash[:danger] = "Não foi possível adicionar as aulas!"
					render :new
				end
			end
		end
	end

	private

	def lesson_params
		params.require(:lesson).permit(:date, :status, :classroom_id)
	end
	
	def set_lesson
		@lesson = Lesson.find(params[:id])
	end

	def set_projects
		@projects = Project.all
	end

	def weekdays_collection
    [
      ['Monday', 1],
      ['Tuesday', 2],
      ['Wednesday', 3],
      ['Thursday', 4],
      ['Friday', 5]
    ]
  end
	helper_method :weekdays_collection
end

app/controllers/backoffice/programs_controller.rb
class Backoffice::ProgramsController < ApplicationController
  def index
  end
end

app/controllers/backoffice/projects_controller.rb
class Backoffice::ProjectsController < ApplicationController
	before_action :authenticate_admin!
	before_action :set_project, only: :show
	layout 'admins'

	def index
		@projects = Project.all
	end

	def show
	end

	private

	def set_project
		@project = Project.find(params[:id])
	end
end

app/controllers/backoffice/user_profiles_controller.rb
class Backoffice::UserProfilesController < ApplicationController
	before_action :authenticate_admin!
	before_action :set_user_profile, only: :show
	before_action :set_rooms, only: :new
	layout 'admins'

	def index
		@user_profiles = UserProfile.order(:first_name).page(params[:page]).search(params)
	end

	def show
		@user_profile.enrollments.each do |enroll|
			@rooms = Classroom.where(project_id: enroll.project_id, ceic_id: enroll.ceic_id)
		end
	end

	def new
		@user_profile = UserProfile.new
		@user_profile.build_user
		@user_profile.build_address
	end

	def create
		@user_profile = UserProfile.new(user_profile_params)
		if @user_profile.save
			redirect_to backoffice_user_profile_path(@user_profile), notice: t('devise.registrations.signed_up', resource_name: @user_profile.first_name)
		else
			@rooms = Classroom.where(project_id: 1, ceic_id: 1)
			@user_profile.build_user
			@user_profile.build_address
			render :new
		end
	end

	private

	def set_user_profile
		@user_profile = UserProfile.find(params[:id])
	end
	
	def set_rooms
		@rooms = Classroom.where(project_id: 1, ceic_id: 1)
	end

	def user_profile_params
		params.require(:user_profile).permit(
			:first_name,
			:last_name,
			:birthdate,
			:genre,
			:father_name,
			:mother_name,
			:school_id,
			:active,
			user_attributes: [:email,	:password, :password_confirmation],
			phone_numbers_attributes: [:id, :number, :description, :_destroy],
			address_attributes: [:street, :number, :neighborhood, :city, :state, :zipcode],
			enrollments_attributes: [:canceled, :project_id, :ceic_id, :classroom_id, :created_at, :_destroy]
		)
	end
end

app/helpers/backoffice/admin_profiles_helper.rb
module Backoffice::AdminProfilesHelper
end

app/helpers/backoffice/analytics_helper.rb
module Backoffice::AnalyticsHelper
end

app/helpers/backoffice/attendances_helper.rb
module Backoffice::AttendancesHelper
end

app/helpers/backoffice/classrooms_helper.rb
module Backoffice::ClassroomsHelper
end

app/helpers/backoffice/educ_profiles_helper.rb
module Backoffice::EducProfilesHelper
end

app/helpers/backoffice/enrollments_helper.rb
module Backoffice::EnrollmentsHelper
end

app/helpers/backoffice/programs_helper.rb
module Backoffice::ProgramsHelper
end

app/helpers/backoffice/projects_helper.rb
module Backoffice::ProjectsHelper
end

app/helpers/backoffice/user_profiles_helper.rb
module Backoffice::UserProfilesHelper
end

app/views/backoffice/admin_profiles/_error_messages.html.erb
<% if @admin_profile.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false" class="flex p-2 bg-red-100 border border-red-400 text-sm font-medium text-red-700 py-2 rounded-lg justify-center mx-8 sm:mx-auto max-w-sm">
		<svg viewBox="0 0 24 24" class="text-red-600 w-5 h-5 sm:w-5 sm:h-5 mr-3">
			<path fill="currentColor"
				d="M11.983,0a12.206,12.206,0,0,0-8.51,3.653A11.8,11.8,0,0,0,0,12.207,11.779,11.779,0,0,0,11.8,24h.214A12.111,12.111,0,0,0,24,11.791h0A11.766,11.766,0,0,0,11.983,0ZM10.5,16.542a1.476,1.476,0,0,1,1.449-1.53h.027a1.527,1.527,0,0,1,1.523,1.47,1.475,1.475,0,0,1-1.449,1.53h-.027A1.529,1.529,0,0,1,10.5,16.542ZM11,12.5v-6a1,1,0,0,1,2,0v6a1,1,0,1,1-2,0Z">
			</path>
		</svg>
		<ul>
			<%= t("errors.messages.not_saved", count: @admin_profile.errors.count, resource: @admin_profile.class.model_name.human.downcase) %>
			<% @admin_profile.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/backoffice/admin_profiles/edit.html.erb
<div class="flex flex-col justify-center m-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <div class="text-2xl text-center text-gray-900 font-bold"><%= t('devise.registrations.edit.title', resource: @admin_profile.model_name.human) %></div>
			<%= render "backoffice/admin_profiles/error_messages", resource: @admin_profile %>
			<%= form_with model: [:backoffice, @admin_profile], html: { method: :put, class:"bg-gray-50 shadow-lg rounded-md p-8 my-4" } do |f| %>
				<%= f.label :name, class:"p-4 text-sm font-medium text-gray-900" %>
				<%= f.text_field :name, **input_options %>
				<%= f.label :email, class:"p-4 text-sm font-medium text-gray-900"%>
				<%= f.email_field :email, autofocus: true, autocomplete: "email", **input_options %>
				<div class="field">
					<%= f.label :password, class:"p-4 text-sm font-medium text-gray-900" %> <i class="text-sm">(leaveeeee blank if you don't want to change it)</i>
					<%= f.password_field :password, autocomplete: "new-password", **input_options %>
					<% if @minimum_password_length %>
						<em><%= @minimum_password_length %> characters minimum</em>
					<% end %>
				</div>

				<div class="field">
					<%= f.label :password_confirmation, class:"p-4 text-sm font-medium text-gray-900" %>
					<%= f.password_field :password_confirmation, autocomplete: "new-password", **input_options %>
				</div>

				<div class="field">
					<%= f.label :current_password, class:"p-4 text-sm font-medium text-gray-900" %><i class="text-sm"><%= t('devise.registrations.edit.we_need_your_current_password_to_confirm_your_changes') %></i>
					<%= f.password_field :current_password, autocomplete: "current-password", **input_options %>
				</div>

				<div class="actions">
					<%= f.submit t('devise.registrations.edit.update'), class:"mt-4 px-4 justify-center rounded-md bg-sky-600 py-2 text-sm font-semibold text-white hover:bg-sky-700" %>
				</div>
			<% end %>
			<div class="flex flex-wrap justify-center mt-8 text-sm font-medium text-gray-900">
				<%= link_to t('devise.shared.links.back'), :back %>
			</div>
		</div>
	</div>
</div>

app/views/backoffice/admin_profiles/index.html.erb
<div class="px-4 md:mt-8 mb-16 text-gray-800">
  <div class="p-5">
    <div class="bg-white border rounded shadow">
      <div class="flex flex-wrap">
        <div class="w-1/2 border-b p-3 text-lg font-bold uppercase text-gray-600">
          <%= @admin_profiles.model_name.human(count: 2) %>
        </div>
        <div class="w-1/2 border-b p-3 text-sm text-right font-bold text-gray-600">
					<%= link_to new_backoffice_admin_profile_path, class:"text-cyan-600 hover:text-gray-500" do %>
						<i class="fas fa-user-plus mr-1"></i><span class="text-sm invisible sm:visible"><%= t('devise.registrations.new.sign_up', resource: @admin_profiles.model_name.human) %></span>
					<% end %>
				</div>
      </div>
      <div class="p-5">
        <div class="overflow-x-auto">
          <div class="table w-full text-gray-700">
            <div class="table-header-group">
              <div class="table-row font-bold text-left text-blue-900">
                <% %w[id name email created_at].each do |attribute| %>
                  <% if @admin_profiles.first.attributes.key?(attribute) %>
                    <div class="table-cell px-4 py-2"><%= i18n_attributes(@admin_profiles, attribute) %></div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="table-row-group">
              <% @admin_profiles.each do |admin| %>
                <a href="<%= backoffice_admin_profile_path(admin) %>" class="table-row hover:bg-gray-100">
                  <div class="table-cell px-4 py-2"><%= admin.id %></div>
                  <div class="table-cell px-4 py-2 whitespace-nowrap"><%= admin.name %></div>
                  <div class="table-cell px-4 py-2 whitespace-nowrap"><%= admin.admin.email %></div>
                  <div class="table-cell px-4 py-2"><%= l(admin.created_at.to_date) %></div>
                </a>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/admin_profiles/new.html.erb
<div class="flex flex-col justify-center m-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <div class="text-2xl text-center text-gray-900 font-bold">Cadastrar <%= @admin_profile.model_name.human %></div>
		<%= render "backoffice/admin_profiles/error_messages", resource: @admin_profiles %>
    <%= form_with model: [:backoffice, @admin_profile], html: { class:"bg-gray-50 shadow-lg rounded-md p-8 my-4" } do |f| %>
			<%= f.label :name, class:"p-4 text-sm font-medium text-gray-900" %>
        <%= f.text_field :name, autofocus: true, **input_options %>
        <%= f.label :email, class:"p-4 text-sm font-medium text-gray-900" %><br />
        <%= f.email_field :email, autocomplete: "email", **input_options %>
			
      <div class="field">
        <%= f.label :password, class:"p-4 text-sm font-medium text-gray-900" %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "new-password", **input_options %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation, class:"p-4 text-sm font-medium text-gray-900" %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password", **input_options %>
      </div>

      <div class="actions">
        <%= f.submit "Enviar", class:"mt-4 px-4 justify-center rounded-md bg-sky-600 py-2 text-sm font-semibold text-white hover:bg-sky-700" %>
      </div>
    <% end %>
    <div class="flex flex-wrap justify-center mt-8 text-sm font-medium text-gray-900">
			<%= link_to t('devise.shared.links.back'), :back %>
		</div>
  </div>
</div>

app/views/backoffice/admin_profiles/show.html.erb
<!--Container-->
<div class="px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">
	<div class="p-5">
		<!--Table Card-->
		<div class="bg-white border rounded shadow">
			<div class="flex flex-wrap">
				<div class="w-1/2 border-b p-3 text-lg font-bold uppercase text-gray-600">
					<%= @admin_profile.model_name.human %>
				</div>
				<div class="w-1/2 border-b p-3 text-lg font-bold text-gray-600">
					<div class="text-sm float-right">
						<%= link_to backoffice_admin_profiles_path, class:"text-cyan-600 hover:text-gray-500" do %>
							<i class="fas fa-users mr-1"></i><span class="text-sm"><%= @admin_profile.model_name.human(count: 2) %></span>
						<% end %>
					</div>
				</div>
			</div>
			<div class="p-5">
				<div class="overflow-x-auto">
					<table class="w-full p-5 text-gray-700">
						<thead>
							<tr>
								<% %w[id name email created_at].each do |attribute| %>
									<% if @admin_profile.attributes.key?(attribute) %>
										<th class="text-blue-900 px-4 whitespace-nowrap"><%= @admin_profile.class.human_attribute_name(attribute) %>:</th>
										<td class="whitespace-nowrap"><%= attribute == 'created_at'? l(@admin_profile[attribute].to_date) : @admin_profile[attribute] %><td>
									<% end %>
								<% end %>
								<td ><%= link_to edit_backoffice_admin_profile_path(@admin_profile), class:"font-bold text-lime-500 hover:text-gray-500" do %>
									<i class="fas fa-user-edit fa-fw mr-1"></i><span class="invisible sm:visible text-sm"><%= t('devise.shared.links.edit')%></span><% end %>
								</td>
								<td><%= button_to admin_registration_path, method: :delete, class:"font-bold text-red-500 hover:text-gray-500" do %>
									<i class="fas fa-user-minus fa-fw mr-1 ml-3"></i><span class="invisible sm:visible text-sm"><%= t('devise.registrations.edit.cancel_my_account', resource_name: @admin_profile.name)%></span><% end %>
								</td>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<!--/table Card-->
	</div>
	<!--/ Console Content-->
</div>
<!--/container-->
<footer class="bg-white border-t border-gray-400 shadow">
	<div class="container max-w-md mx-auto flex py-8">
		<div class="w-full mx-auto flex flex-wrap">
			<div class="flex w-full md:w-1/2 ">
				<div class="px-8">
					<h3 class="font-bold text-gray-900">About</h3>
					<p class="py-4 text-gray-600 text-sm">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel mi ut felis tempus commodo nec id erat. Suspendisse consectetur dapibus velit ut lacinia.
					</p>
				</div>
			</div>
			<div class="flex w-full md:w-1/2">
				<div class="px-8">
					<h3 class="font-bold text-gray-900">Social</h3>
					<ul class="list-reset items-center text-sm pt-3">
						<li>
							<a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Add social link</a>
						</li>
						<li>
							<a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Add social link</a>
						</li>
						<li>
							<a class="inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-1" href="#">Add social link</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</footer>