config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

	devise_for :users
  devise_for :educs
  devise_for :admins

	namespace :backoffice do
		resources :admin_profiles,
		:educ_profiles,
		:user_profiles,
		:programs,
		:projects,
		:enrollments,
		:classrooms,
		:lessons,
		:attendances
	 get '/analytics', to: 'analytics#index'
	 get '/users_reports', to: 'analytics#users_reports'
	 get '/enrollments_reports', to: 'analytics#enrollments_reports'
	 get '/projects_reports', to: 'analytics#projects_reports'
	 get '/project_report/:id', to: 'analytics#project_report', as: 'project_report'
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@user = User
		@admin = Admin
		@educ = Educ
  end
end

app/helpers/home_helper.rb
module HomeHelper
	def sign_in_or_out_link(model, sign_in_path, sign_out_path)
    resource = model.to_s.downcase
		if public_send("#{resource}_signed_in?")
      button_to sign_out_path, method: :delete, class: "font-medium text-cyan-600 pr-4 hover:text-gray-500 inline-block" do
        content_tag(:i, '', class: icon_class(resource)) + "#{i18n_models(model)} #{t('devise.shared.links.sign_out')}"
			end
    else
      link_to sign_in_path, id: "#{resource}In", class: "font-medium text-cyan-600 pr-4 hover:text-gray-500 inline-block" do
        content_tag(:i, '', class: icon_class(resource)) + "#{i18n_models(model)} #{t('devise.shared.links.sign_in')}"
			end
    end
  end
	
  def icon_class(resource)
    case resource
    when "user"
      "fas fa-user fa-fw inline-block pt-2 mr-1"
    when "admin"
      "fas fa-users fa-fw inline-block pt-2 mr-1"
    when "educ"
      "fas fa-chalkboard-teacher fa-fw inline-block pt-2 mr-1"
    else
      ""
    end
  end
end

app/views/home/index.html.erb
<nav class="bg-white fixed w-full z-10 top-0 shadow">
	<div class="container mx-auto flex flex-wrap">
		<div class="flex flex-wrap">
			<div class="px-2 py-4 relative text-sm">
				<%= sign_in_or_out_link(@user, new_user_session_path, destroy_user_session_path) %>
				<%= sign_in_or_out_link(@admin, new_admin_session_path, destroy_admin_session_path) %>
				<%= sign_in_or_out_link(@educ, new_educ_session_path, destroy_educ_session_path) %>
			</div>
		</div>
	</div>
</nav>